### PR TITLE
iNZightTools refactor

### PR DESCRIPTION
**Pull request by szmsu2011**

### CODE REVIEW

**Comment by szmsu2011** [comment]
TODO list:
- [ ] Display issue for `chron::chron()` and `tsibble::year_*()` objects
- [ ] Testing failures due to uninstalled `surveyspec` package
- [ ] New features ...

**Comment by tmelliott** [comment]
Just while I'm thinking about it - please keep the `NEWS` file updated with *all* changes/additions (given user-visible changes it is important to have a good record of everything).

**Comment by tmelliott** [comment]
- [ ] widths of 'Aggregate dt window' might make the window too large on small screens

**Comment by tmelliott** [comment]
Created issue #423 to work on separately from this PR.
Merging into dev - please push future changes to new branches (`feature/<feature>`, `bugfix/<bugfix>` etc)

**Pull request merged**
